mysite/lib/urls.py
# lib/urls.py
from django.urls import path
from . import views1
from . import views

#添加这行 命名空间
app_name = 'lib'

urlpatterns = [
    path('', views1.index, name='index'),
    path('index/', views1.index, name='index'),
    path('detail/', views.detail, name='detail'),
    path('process/', views.process, name='process'),
    path('addBook/', views.addBook, name='addBook'),
    path('update_info/<int:book_id>', views.update_info, name='update_info'),
    path('updateBook/<int:book_id>', views1.updateBook, name='updateBook'),
    path('delBook/<int:book_id>', views.delBook, name='delBook'),
]

mysite/mysite/urls.py
# mysite/mysite/urls.py
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    # path('upld/', include('easy_uploader.urls', namespace="easy_uploader")),
    url(r'^upld/', include('easy_uploader.urls', namespace="easy_uploader")),
    path('lib/', include('lib.urls')),
    path('admin/', admin.site.urls),
    path('', include('lib.urls')),
    path('hello/', include('hello.urls')),
    path('polls/', include('polls.urls')),
]


mysite/lib/models.py
from django.db import models
# lib/models.py
# Create your models here.

class Book(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=100)
    pub_house = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')


mysite/lib/views.py
# mysite/lib/views.py
from django.shortcuts import render
from .models import Book
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone


def process(request):
    if request.method == 'POST':
        if 'button_1' in request.POST:
            # ボタン1がクリックされた場合の処理
            print("button_1")
            return HttpResponseRedirect(reverse('lib:detail'))
        elif 'button_2' in request.POST:
            # ボタン2がクリックされた場合の処理
            print("button_2")
            return HttpResponseRedirect(reverse('polls:question'))


def detail(request):
    book_list = Book.objects.order_by('-pub_date')[:5]
    context = {'book_list': book_list}
    return render(request, 'lib/detail1.html', context)


def addBook(request):
    if request.method == 'POST':
        temp_name = request.POST['name']
        temp_author = request.POST['author']
        temp_pub_house = request.POST['pub_house']

    from django.utils import timezone
    temp_book = Book(name=temp_name, author=temp_author, pub_house=temp_pub_house, pub_date=timezone.now())
    temp_book.save()

    #重定向
    return HttpResponseRedirect(reverse('lib:detail'))


def update_info(request,book_id):
    if request.method == 'POST':
        temp_name = request.POST['name']
        temp_author = request.POST['author']
        temp_pub_house = request.POST['pub_house']

    from django.utils import timezone
    Book.objects.filter(id=book_id).update(name=temp_name,author=temp_author,pub_house=temp_pub_house,pub_date=timezone.now())
    #重定向
    return HttpResponseRedirect(reverse('lib:detail'))


def delBook(request,book_id):
    bookID = book_id
    Book.objects.filter(id=bookID).delete()
    # 重定向
    return HttpResponseRedirect(reverse('lib:detail'))





mysite/lib/templates/lib/band.html
{% block content1 %}
<p>customization</p>
{% endblock %}


{% extends "myapp1/base.html" %}
{% block content1 %}
<h1>Hello, {{fname}}!</h1>
{% endblock %}

mysite/lib/templates/lib/detail1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Test</title>
</head>
<body>
<table>
    <tr>
        <td>Book name</td>
        <td>Author</td>
        <td>Publishing House</td>
        <td>Publish Date</td>
    </tr>
{% for book in book_list.all %}
    <tr>
        <td>{{ book.name }}</td>
        <td>{{ book.author }}</td>
        <td>{{ book.pub_house }}</td>
        <td>{{ book.pub_date }}</td>
        <td><a href="{% url 'lib:updateBook' book.id %}">Modify</a></td>
        <td><a href="{% url 'lib:delBook' book.id %}">Delete</a></td>
    </tr>
{% endfor %}
</table>
<form action="{% url 'lib:addBook' %}" method="post" name="addBook">
    {% csrf_token %}
    <p><span>Book name：</span><input type="text"  name="name"></p>
    <p><span>Author：</span><input type="text"  name="author"></p>
    <p><span>Publishing House：</span><input type="text"  name="pub_house"></p>
    <input type="submit" value="Add">
</form>
</body>
</html>

mysite/lib/templates/lib/detail_update.html
<!--lib/templates/lib/detail_update.html-->
<html lang="en">
<h1>Book List</h1>
<head>
</head>
<body>
{% for book in book_list.all %}
<form action="{% url 'lib:update_info' book.id %}" method="post" name="update_info">
    {% csrf_token %}
<table>

    <p><span>Book name：</span><input type="text"  name="name" value={{ book.name }}> </p>
    <p><span>Author：</span><input type="text"  name="author" value={{ book.author }}></p>
    <p><span>Publishing House：</span><input type="text"  name="pub_house" value={{ book.pub_house }}></p>

</table>
    {% endfor %}
    <input type="submit" value="Modify">
</form>

</body>

</html>



mysite/lib/templates/lib/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>welcome</title>
</head>
<body align="center">
<!--<form action="{% url 'lib:detail' %}" method="post" name="detail">-->
<form action="{% url 'lib:process' %}" method="post" name="process">
    {% csrf_token %}
<!--    调用views1.py传递过来的值，然后显示-->
    <p>{{ now }}</p>
    <p>{{ qiu }}</p>
<table align="center">
    <tr align="center">
        Welcome back,My private Bookstore！
    </tr>
    <tr align="center">
        <p>
            <input type="submit" name="button_1" value="Bookstore Enter">
            <input type="submit" name="button_2" value="Vote">
        </p>
    </tr>
</table>
    <!--<input type="submit" value="进入">-->
</form>

<HR>
<form align=center action="/hello/upload" method="get" name="index">
<!--    {% csrf_token %}-->
    <tr>
        <td><p>funtion two, uploadable a number of files and then push something image to prediction.</p></td>
        <td><input type="submit" value="Upload Files to Prediction"></td>
    </tr>
</form>

</body>
</html>