mysite/lib/urls.py
# lib/urls.py
from django.urls import path
from . import views1
from . import views

#添加这行 命名空间
app_name = 'lib'

urlpatterns = [
    path('', views1.index, name='index'),
    path('index/', views1.index, name='index'),
    path('detail/', views.detail, name='detail'),
    path('process/', views.process, name='process'),
    path('addBook/', views.addBook, name='addBook'),
    path('update_info/<int:book_id>', views.update_info, name='update_info'),
    path('updateBook/<int:book_id>', views1.updateBook, name='updateBook'),
    path('delBook/<int:book_id>', views.delBook, name='delBook'),
]

mysite/mysite/urls.py
# mysite/mysite/urls.py
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    # path('upld/', include('easy_uploader.urls', namespace="easy_uploader")),
    url(r'^upld/', include('easy_uploader.urls', namespace="easy_uploader")),
    path('lib/', include('lib.urls')),
    path('admin/', admin.site.urls),
    path('', include('lib.urls')),
    path('hello/', include('hello.urls')),
    path('polls/', include('polls.urls')),
]


mysite/polls/urls.py
# polls/urls.py
from django.urls import path
from . import questions
from . import choice

#添加这行 命名空间
app_name = 'polls'

urlpatterns = [
    path('question/', questions.question, name='question'),
    # path('detail/', views.detail, name='detail'),
    # path('process/', views.process, name='process'),
    path('addQuestion/', questions.addQuestion, name='addQuestion'),
    path('choice/', questions.choice, name='choice'),
    path('replyQuestion/<int:question_id>', questions.replyQuestion, name='replyQuestion'),
    # path('updateBook/<int:book_id>', views1.updateBook, name='updateBook'),
    path('delQuestion/<int:question_id>', questions.delQuestion, name='delQuestion'),
]

mysite/polls/models.py
from django.db import models
from django.utils import timezone
from django.utils.timezone import localtime


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField(default=timezone.now())

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.CharField(max_length=20)

    def __str__(self):
        return self.choice_text

mysite/polls/templates/polls/choice.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>question_reply</title>
</head>
<body>
<table align=center border="1">
    <tr>
        <td>Question</td>
        <td>Publish Question</td>
    </tr>
    <tr>
        <td>{{ question_info.question_text }}</td>
        <td>{{ question_info.pub_date }}</td>
    </tr>
</table>

<!--html分割线-->
<HR style="FILTER: alpha(opacity=100,finishopacity=0,style=3)" width="50%" color=#987cb9 SIZE=3>

<table align=center border="1">
    <tr>
        <td>Reply Content</td>
        <td>Attitude</td>
    </tr>
    {% for choice in choice_info.all %}
    <tr>
        <td>{{ choice.choice_text }}</td>
        <td>{{ choice.votes }}</td>
    </tr>
    {% endfor %}
</table>

<!--        for endfor if elif endif的使用例子-->
<!--        {%for i in choice.votes%}-->
<!--            {% if i == '0' %}-->
<!--            {% with str="赞同 " %}-->
<!--{% endwith %}-->
<!--            {% elif i == '1' %}-->
<!--            {% with str=str|add:"反对 " %}-->
<!--{% endwith %}-->
<!--            {% elif i == '2' %}-->
<!--            {% with str=str|add:"无视 " %}-->
<!--{% endwith %}-->
<!--            {% endif %}-->
<!--        {% endfor %}-->


<!--        字符串拼接，在html里面拼接很麻烦，建议在py文件里面拼接-->
<!--        {% with template="shop/"|add:"abc"|add:"/base.html" %}-->
<!--        {% with template=template|add:"abc" %}-->
<!--        <td>{{template}}</td>-->
<!--        {% endwith %}-->
<!--        {% endwith %}-->


<style>
    input[type="checkbox"] {
        display: none;
    }

     label {
        display: inline-block;
        border-radius: 20px;
        text-align: center;
        text-decoration: none;
        border: solid 1px #ccc;
        transition: 0.25s;
        padding: 6px 18px;
        cursor: pointer;
        font-size: 14px;
        margin: 3px;
    }

    input[type="checkbox"]:checked + label {
        background: #00809d;
        color: #fff;
    }
</style>

<form align=center action="{% url 'polls:choice' %}" method="post" name="choice">
    {% csrf_token %}
    <p><span>Reply Question：</span><input type="text"  name="choice_text"></p>
    <p><input type="checkbox" name="tags" value="0" id="id_tags_0">
        <label for="id_tags_0">Agree</label>
        <input type="checkbox" name="tags" value="1" id="id_tags_1">
        <label for="id_tags_1">Against</label>
        <input type="checkbox" name="tags" value="2" id="id_tags_2">
        <label for="id_tags_2">Ignore</label>
    </p>
    <input id="question_id" name="question_id" type="hidden" value={{ question_info.id }}>
    <input type="submit" value="Push Question">
</form>

<HR>
<form align=center action="{% url 'polls:question' %}" method="post" name="return">
    {% csrf_token %}
    <input type="submit" value="Previous">
</form>
</body>
</html>

mysite/polls/templates/polls/question.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Question Show</title>
</head>
<body>
<table align=center>
    <tr>
        <td>Question</td>
        <td>Publish Date</td>
    </tr>
{% for question in question_list.all %}
    <tr>
        <td>{{ question.question_text }}</td>
        <td>{{ question.pub_date }}</td>
        <td><a href="{% url 'polls:replyQuestion' question.id %}">Reply Question</a></td>
        <td><a href="{% url 'polls:delQuestion' question.id %}">Delete Question</a></td>
    </tr>
{% endfor %}
</table>
<form align=center action="{% url 'polls:addQuestion' %}" method="post" name="addQuestion">
    {% csrf_token %}
    <p><span>Question：</span><input type="text"  name="question_text"></p>
    <input type="submit" value="Push Question">
</form>

<HR>
<form align=center action="{% url 'lib:index' %}" method="post" name="return">
    {% csrf_token %}
    <input type="submit" value="Previous">
</form>
</body>
</html>