mysite/easy_uploader/urls.py
from django.conf.urls import url
from . import views

app_name = 'easy_uploader'

urlpatterns = [
    # FileのCRUD
    url(r'^$', views.FileIndexView.as_view(), name='file_index'),
    url(r'^file/category/(?P<category_pk>[0-9]+)/$',
        views.FileCategoryView.as_view(), name='file_category'),
    url(r'^file/create/$', views.FileCreateView.as_view(), name='file_create'),
    url(r'^file/create/(?P<category_pk>[0-9]+)/$',
        views.FileCreateView.as_view(), name='file_create'),
    url(r'^file/update/(?P<pk>[0-9]+)/$',
        views.FileUpdateView.as_view(), name='file_update'),
    url(r'^file/delete/(?P<pk>[0-9]+)/$',
        views.FileDeleteView.as_view(), name='file_delete'),

    # 間接リンク
    url(r'^indirect/link/(?P<pk>[0-9]+)/$',
        views.indirect_link, name='indirect_link'),

    # CategoryのCRUD
    url(r'^category/$',
        views.CategoryIndexView.as_view(), name='category_index'),
    url(r'^category/create/$',
        views.CategoryCreateView.as_view(), name='category_create'),
    url(r'^category/update/(?P<pk>[0-9]+)/$',
        views.CategoryUpdateView.as_view(), name='category_update'),
    url(r'^category/delete/(?P<pk>[0-9]+)/$',
        views.CategoryDeleteView.as_view(), name='category_delete'),
]

mysite/lib/urls.py
# lib/urls.py
from django.urls import path
from . import views1
from . import views

#添加这行 命名空间
app_name = 'lib'

urlpatterns = [
    path('', views1.index, name='index'),
    path('index/', views1.index, name='index'),
    path('detail/', views.detail, name='detail'),
    path('process/', views.process, name='process'),
    path('addBook/', views.addBook, name='addBook'),
    path('update_info/<int:book_id>', views.update_info, name='update_info'),
    path('updateBook/<int:book_id>', views1.updateBook, name='updateBook'),
    path('delBook/<int:book_id>', views.delBook, name='delBook'),
]

mysite/mysite/urls.py
# mysite/mysite/urls.py
"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/2.1/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import include, path
from django.conf.urls import url

urlpatterns = [
    # path('upld/', include('easy_uploader.urls', namespace="easy_uploader")),
    url(r'^upld/', include('easy_uploader.urls', namespace="easy_uploader")),
    path('lib/', include('lib.urls')),
    path('admin/', admin.site.urls),
    path('', include('lib.urls')),
    path('hello/', include('hello.urls')),
    path('polls/', include('polls.urls')),
]


mysite/easy_uploader/models.py
import os
from django.db import models
from django.utils import timezone


class Category(models.Model):
    """カテゴリ."""
    name = models.CharField('カテゴリ名', max_length=255)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.name


def get_upload_to(instance, filename):
    """upload_toを動的に指定する."""
    try:
        path = os.path.join(str(instance.category.name), filename)
        print("qiulongquan_path={}".format(path))
    except:
        path = os.path.join('default', filename)
    return path


def default_category():
    """デフォルトのカテゴリを返す（まだなければ作る）."""
    category, _ = Category.objects.get_or_create(name='default')
    return category


class File(models.Model):
    """アップロードするファイル."""

    title = models.CharField('タイトル', max_length=255, blank=True)
    category = models.ForeignKey(
        Category, verbose_name='カテゴリ', on_delete=models.PROTECT,
        default=default_category,
    )
    src = models.FileField('ファイル', upload_to=get_upload_to)
    created_at = models.DateTimeField('作成日', default=timezone.now)

    def __str__(self):
        return self.title

    def get_filename(self):
        """ファイル名を返す関数"""
        return os.path.basename(self.src.name)

mysite/easy_uploader/forms.py
from django import forms
from .models import File, Category


class FileForm(forms.ModelForm):
    """Fileモデルのフォーム."""

    class Meta:
        model = File
        fields = '__all__'
        widgets = {
            'title': forms.TextInput(attrs={
                'class': "form-control",
            }),
            'file': forms.ClearableFileInput(attrs={
                'class': "form-control-file",
            }),
            'category': forms.Select(attrs={
                'class': "form-control",
            }),
            'created_at': forms.DateTimeInput(attrs={
                'class': 'form-control',
            }),
        }


class CategoryForm(forms.ModelForm):
    """Categoryモデルのフォーム."""

    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'name': forms.TextInput(attrs={
                'class': "form-control",
            }),
            'created_at': forms.DateTimeInput(attrs={
                'class': 'form-control',
            }),
        }

mysite/easy_uploader/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import redirect, get_object_or_404
from django.views import generic

from .forms import FileForm, CategoryForm
from .models import File, Category


class FileIndexView(generic.ListView):
    """ファイル一覧."""

    model = File
    queryset = File.objects.order_by('-created_at')
    paginate_by = 20


def indirect_link(request, pk):
    """間接リンク。実際のURLへリダイレクト."""
    file = get_object_or_404(File, pk=pk)
    print("qiulongquan_file={}".format(file.src.url))
    return redirect(file.src.url)


class FileCategoryView(generic.ListView):
    """カテゴリ別のファイル一覧."""

    model = File
    paginate_by = 20

    def get_queryset(self):
        """カテゴリでfilter."""
        category_pk = self.kwargs['category_pk']
        print("qiulongquan_category_pk={}".format(category_pk))
        return File.objects.filter(
            category__pk=category_pk).order_by('-created_at')

    def get_context_data(self, *args, **kwargs):
        """カテゴリのpkをテンプレートへ渡す."""
        context = super().get_context_data(*args, **kwargs)
        context['category_pk'] = self.kwargs.get('category_pk')
        return context


class FileCreateView(LoginRequiredMixin, generic.CreateView):
    """ファイルの作成."""

    model = File
    form_class = FileForm
    success_url = reverse_lazy('easy_uploader:file_index')

    def get_initial(self):
        """カテゴリの指定があれば、そのカテゴリを選択状態に."""
        initial = super().get_initial()
        initial['category'] = self.kwargs.get('category_pk')
        return initial

    def form_valid(self, form):
        file = form.save()
        action = self.request.POST['action']

        # 保存してもう一つ追加ボタンのとき
        if action == 'send_more':
            return redirect('easy_uploader:file_create', file.category.pk)

        # それ以外、送信ボタン        
        else:
            return redirect('easy_uploader:file_index')

          
class FileUpdateView(LoginRequiredMixin, generic.UpdateView):
    """ファイルの更新."""

    model = File
    form_class = FileForm
    success_url = reverse_lazy('easy_uploader:file_index')

    def form_valid(self, form):
        file = form.save()
        action = self.request.POST['action']

        # 保存してもう一つ追加ボタンのとき
        if action == 'send_more':
            return redirect('easy_uploader:file_create', file.category.pk)

        # それ以外、送信ボタン        
        else:
            return redirect('easy_uploader:file_index')


class FileDeleteView(LoginRequiredMixin, generic.DeleteView):
    """ファイルの削除."""

    model = File
    success_url = reverse_lazy('easy_uploader:file_index')


class CategoryIndexView(generic.ListView):
    """カテゴリの一覧."""

    model = Category
    queryset = Category.objects.order_by('-created_at')
    paginate_by = 20


class CategoryCreateView(LoginRequiredMixin, generic.CreateView):
    """カテゴリの作成."""

    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('easy_uploader:category_index')


class CategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    """カテゴリの更新."""

    model = Category
    form_class = CategoryForm
    success_url = reverse_lazy('easy_uploader:category_index')


class CategoryDeleteView(LoginRequiredMixin, generic.DeleteView):
    """カテゴリの削除."""

    model = Category
    success_url = reverse_lazy('easy_uploader:category_index')

mysite/easy_uploader/templates/easy_uploader/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- Required meta tags always come first -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
 
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    
    <!-- Sweet Alert -->
    <link rel="stylesheet" type="text/css" href="https://torina.top/media/sweetalert/sweetalert.css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="{% static 'easy_uploader/css/main.css' %}">
  </head>
  <body>
    <nav class="navbar fixed-top navbar-toggleable-md navbar-inverse bg-info">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2">
        &#9776;
      </button>
      <div class="collapse navbar-collapse" id="exCollapsingNavbar2">
      <div class="container">
        <ul class="nav navbar-nav">
         <li class="nav-item">
            <a class="nav-link {% block file_page %}{% endblock %}" href="{% url 'easy_uploader:file_index' %}">File</a>
          </li>
         <li class="nav-item">
            <a class="nav-link {% block category_page %}{% endblock %}" href="{% url 'easy_uploader:category_index' %}">Category</a>
          </li>
        </ul>
        </div>
      </div>
    </nav>
      <section class="jumbotron text-center">
        <div class="container">
          <h1>アップローダーサンプル</h1>
          <p class="lead text-muted">
            アップローダーのサンプルです。Bootstrap4を使っています。<br>
            <a href="https://github.com/naritotakizawa/django-easy-uploader" target="_blank">ソースコード</a>
          </p>
        </div>
      </section>
    {% block content %} {% endblock %}

    <!-- jQuery first, then Tether, then Bootstrap JS. -->
   <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js" integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    
    <!-- Sweet Alert -->
    <script src="https://torina.top/media/sweetalert/sweetalert.min.js"></script>

    <script>
    $('.delete').on('click',function(e){
        e.preventDefault();
        var form = $(this).parents('form');
        swal({
            title: "確認",
            text: "削除してよろしいですか？",
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Yes, delete it!",
            closeOnConfirm: false
        }, function(isConfirm){
            if (isConfirm) form.submit();
        });
    });
    </script>

  </body>
</html>

mysite/easy_uploader/templates/easy_uploader/category_confirm_delete.html
{% extends "easy_uploader/base.html" %}
{% block category_page %}active{% endblock %}
{% block content %}

  <div class="container">
    <form action="" method="POST" enctype='multipart/form-data'>
	  <div class="text-center">
	    <p>カテゴリ名:{{ category.name }}</p>
	    <button type="submit" class="btn btn-outline-primary">削除する</button>
	    <a href="{% url 'easy_uploader:category_index' %}" class="btn btn-outline-primary">やめる</a>
	  </div>
	  {% csrf_token %}
    </form>
  </div>
{% endblock %}

mysite/easy_uploader/templates/easy_uploader/category_form.html
{% extends "easy_uploader/base.html" %}
{% block category_page %}active{% endblock %}
{% block content %}
  <div class="container">
    <form action="" method="POST" enctype='multipart/form-data'>
      {% for field in form %}
        <div class="form-group row">
          <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">
            {{ field.label_tag }}
          </label>
          <div class="col-sm-10">
            {{ field }}
          </div>
        </div>
      {% endfor %}
      {% csrf_token %}
      <div class="text-center">
        <button type="submit" class="btn btn-outline-primary" value="send" name="action">送信する</button>
        <a href="{% url 'easy_uploader:category_index' %}" class="btn btn-outline-primary">やめる</a>
      </div>
    </form>
  </div>
{% endblock %}

mysite/easy_uploader/templates/easy_uploader/category_list.html
{% extends "easy_uploader/base.html" %}
{% block category_page %}active{% endblock %}
{% block content %}
  <div class="container">
      <a href="{% url 'easy_uploader:category_create' %}" class="btn btn-outline-primary">
          新規作成
      </a>
      <hr>
    <table class="table">
      <thead>
        <tr>
          <th>カテゴリ名</th>
          <th>作成日</th>
          <th>#</th>
        </tr>
      </thead>
      <tbody>
        {% for category in category_list %}
          <tr>
            <td>{{ category.name }}</td>
            <td>{{ category.created_at }}</td>
            <td>
                <a href="{% url 'easy_uploader:category_update' category.pk %}" class="btn btn-outline-primary btn-sm">
                  更新
                </a>
                <form class="delete-form" action="{% url 'easy_uploader:category_delete' category.pk %}" method="POST">
                    <button type="button" class="btn btn-outline-primary btn-sm delete">削除</button>
                    {% csrf_token %}
                </form>
                <a href="{% url 'easy_uploader:file_category' category.pk %}" class="btn btn-outline-primary btn-sm">
                  カテゴリのファイル一覧
                </a>

            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="text-center">
      {% include "easy_uploader/page.html" %}
    </div>
  </div>
{% endblock %}

mysite/easy_uploader/templates/easy_uploader/file_confirm_delete.html
{% extends "easy_uploader/base.html" %}
{% block file_page %}active{% endblock %}
{% block content %}

  <div class="container">
    <form action="" method="POST" enctype='multipart/form-data'>
	  <div class="text-center">
	    <p>タイトル:{{ file.title }}</p>
	    <p>カテゴリ名:{{ file.category.name }}</p>
	    <button type="submit" class="btn btn-outline-primary">削除する</button>
	    <a class="btn btn-outline-primary" href="javascript:void(0);" onclick="window.history.back();">戻る</a>
	  </div>
	  {% csrf_token %}
    </form>
  </div>
{% endblock %}

mysite/easy_uploader/templates/easy_uploader/file_form.html
{% extends "easy_uploader/base.html" %}
{% block file_page %}active{% endblock %}
{% block content %}
  <div class="container">
    <form action="" method="POST" enctype='multipart/form-data'>
      {% for field in form %}
        <div class="form-group row">
          <label for="{{ field.id_for_label }}" class="col-sm-2 col-form-label">
            {{ field.label_tag }}
          </label>
          <div class="col-sm-10">
            {{ field }}
          </div>
        </div>
      {% endfor %}
      {% csrf_token %}
      <div class="text-center">
        <button type="submit" class="btn btn-outline-primary" value="send" name="action">送信する</button>
        <button type="submit" class="btn btn-outline-primary" value="send_more" name="action">送信してもう1つ追加</button>
        <a class="btn btn-outline-primary" href="javascript:void(0);" onclick="window.history.back();">戻る</a>
      </div>
    </form>
  </div>
{% endblock %}

mysite/easy_uploader/templates/easy_uploader/file_list.html
{% extends "easy_uploader/base.html" %}
{% block file_page %}active{% endblock %}
{% block content %}

  <div class="container">
      {% if category_pk %}
      <a href="{% url 'easy_uploader:file_create' category_pk %}" class="btn btn-outline-primary">
          新規作成
      </a>
      {% else %}
      <a href="{% url 'easy_uploader:file_create' %}" class="btn btn-outline-primary">
          新規作成
      </a>      
      {% endif %}
      <hr>
    <table class="table">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>ファイル名</th>
          <th>間接リンク</th>
          <th>カテゴリ</th>
          <th>作成日</th>
          <th>#</th>
        </tr>
      </thead>
      <tbody>
        {% for file in file_list %}
          <tr>
            <td>{{ file.title }}</td>
            <td>{{ file.get_filename }}</td>
            <td>
                <a href="{% url 'easy_uploader:indirect_link' file.pk %}" target="_blank">
                    {% url 'easy_uploader:indirect_link' file.pk %}
                </a>
            </td>
            <td><a href="{% url 'easy_uploader:file_category' file.category.pk %}">{{ file.category.name }}</a></td>
            <td>{{ file.created_at }}</td>
            <td>
                <a href="{% url 'easy_uploader:file_update' file.pk %}" class="btn btn-outline-primary btn-sm">
                  更新
                </a>
                <form class="delete-form" action="{% url 'easy_uploader:file_delete' file.pk %}" method="POST">
                    <button type="button" class="btn btn-outline-primary btn-sm delete">削除</button>
                    {% csrf_token %}
                </form>
                <a href="{{ file.src.url }}" target="_blank" class="btn btn-outline-primary btn-sm">
                  ブラウザで開く
                </a>
                <a href="{{ file.src.url }}" download="{{ file.get_filename }}" class="btn btn-outline-primary btn-sm">
                  ダウンロード
                </a>

            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <div class="text-center">
      {% include "easy_uploader/page.html" %}
    </div>
  </div>
{% endblock %}

mysite/easy_uploader/templates/easy_uploader/page.html
<nav aria-label="Page navigation">
  <ul class="pagination">

      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ link_page }}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?page={{  page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>